#!/bin/python3

import math
import os
import random
import re
import sys

def hourglassSum(arr):
    max_sum = -63
    for i in range(4):
        for j in range(4):
            upper_row = sum(arr[i][j:j+3])
            center = arr[i+1][j+1]
            bottom_row = sum(arr[i+2][j:j+3])
            current_value = upper_row + center + bottom_row
            if current_value>max_sum:
                max_sum = current_value
    return max_sum 

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
